#!/usr/bin/env python3


import os
import sys
import subprocess


def locate_script(args):
    path = os.path.dirname(os.path.realpath(__file__))
    path = os.path.join(path, 'scripts')
    for index, arg in enumerate(args):
        path = os.path.join(path, arg)
        if os.path.isdir(path):
            continue
        elif os.path.isfile(path):
            return {
                'path': path,
                'args': args[index+1:]
            }
        raise FileNotFoundError('Could not find %s.' % path)


def main():
    args = sys.argv[1:]
    if len(args) < 1:
        print("TODO: provide list of available commands.")
        return
    try:
        script = locate_script(args)
    except FileNotFoundError as e:
        print(e)
        return
    try:
        subprocess.check_call(' '.join([script['path']] + script['args']), shell=True)
    except subprocess.CalledProcessError as e:
        print(e)
        return

if __name__ == '__main__':
    main()
